# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./
COPY yarn.lock ./

# Install dependencies
RUN yarn install
RUN yarn add sequelize-cli

# Copy the rest of the API files to the container
COPY . .

# Expose the port on which the API will run
EXPOSE 3000

# Start the API application
RUN chmod +x init-db.sh
ENTRYPOINT [ "./init-db.sh" ]
CMD ["node", "api/index.js"]
